### ISSUE TITLE
Seq Service not starting on boot

### ISSUE THREAD

**Issue by ralsu091** [datalust/seq-releases#606] opened 2017-07-26 15:10 UTC
Seq Version: 4.1.17
Environment: Windows 8.1

After the last update, whenever I restart my machine, I have to manually start the seq service.
I verified that the service is set to start Automatically. The logs don't show any errors.
Here are the logs when I restart my machine:
`{"@t":"2017-07-26T13:54:26.7545721Z","@mt":"Received OS shutdown notification"}
{"@t":"2017-07-26T13:54:26.8225729Z","@mt":"Stopping HTTP listener"}
{"@t":"2017-07-26T13:54:26.8855770Z","@mt":"Signalling for {Workers} background worker(s) to complete","Workers":3,"SourceContext":"Flare.Workers.WorkerPool"}
{"@t":"2017-07-26T13:54:27.3908520Z","@mt":"Stopping {Tasks} scheduled tasks","Tasks":11,"SourceContext":"Seq.Server.Tasks.TaskRunner"}
{"@t":"2017-07-26T13:54:27.3928917Z","@mt":"Stopping broadcast channel","SourceContext":"Flare.Events.Broadcast.BroadcastChannel"}
{"@t":"2017-07-26T13:54:27.5575333Z","@mt":"Seq stopped cleanly"}
`

Then when I manually started the service:
`{"@t":"2017-07-26T14:22:31.4256658Z","@mt":"Seq {SeqVersion} {ProcessWordSize}-bit running on .NET {DotNetVersion} and OS {OSCaption} ({OSVersion}) {OSWordSize}-bit","SeqVersion":"4.1.17","ProcessWordSize":64,"DotNetVersion":"4.0.30319.42000","OSCaption":"Microsoft Windows 8.1 Enterprise","OSVersion":"6.3.9600","OSWordSize":64,"SourceContext":"Seq.Server.Features.Diagnostics.EnvironmentInformationWriter"}
{"@t":"2017-07-26T14:22:32.2640430Z","@mt":"Seq listening on {ListenUris}","ListenUris":["http://localhost:5341/"]}`

If you require more information, please let me know! Thanks a lot for maintaining Seq!

**Comment by nblumhardt** [comment] 2017-07-26 21:38
Hi @ralsu091, thanks for the report.

I've looked into this one and turned up very few clues - the absence of an error in the Seq log suggests that Windows simply isn't attempting to start the service. A check of the Windows event log would be great, if you are able to look for errors at around the time of boot.

Would you mind setting the service to start `Automatic (Delayed Start)` and see whether this resolves the problem? (Delayed auto-start takes another two minutes after boot for the service to come up.)

Best regards,
Nick

**Comment by ralsu091** [comment] 2017-07-27 14:14
Hi @nblumhardt,

Thank you for the reply. I did check the Windows event logs and did not find anything. It's really weird.
I have set the service start to `Automatic (Delayed Start)` and this morning it started successfully.

I'm not sure what was causing the service to not start, but I'm happy with the workaround.

Thanks for the help!

**Comment by nblumhardt** [comment] 2017-07-27 21:45
Thanks for the follow-up, @ralsu091. I'll keep an eye out for a pattern - as far as I can tell, this is some kind of Windows issue, but it'd be interesting to see whether we're doing something particular to trigger it.

All the best,
Nick

**Comment by laurencee** [comment] 2017-07-30 23:28
This just happened to me on one of our production instances.

Seq version 4.1.14
Windows Server 2012 R2 Standard

I had just rebooted to install some patches (KB4025333, KB4020322, KB4025336, KB4025252, KB890830) and noticed the Seq service wasn't running after the machine booted back up so I manually started the service.

**Comment by laurencee** [comment] 2017-07-31 00:18
Just took a look in the event log, I can see the service failed to start. I think the service should probably be setup to Delayed Start by default.

```
The Seq Event Server and Web UI service failed to start due to the following error: 
The service did not respond to the start or control request in a timely fashion.
```

```
A timeout was reached (30000 milliseconds) while waiting for the Seq Event Server and Web UI service to connect.
```

**Comment by nblumhardt** [comment] 2017-07-31 01:12
Thanks for the additional info @laurencee.

I did look into delayed start, but the two-minute delay will be a bit much to bear.

Making the Seq service dependent on another - e.g. networking - might be a decent option. Reopening with that option in mind 👍

**Comment by ralsu091** [comment] 2017-08-08 13:58
@nblumhardt the service didn't start this morning with the Automatic Delayed Start.
I have found an Error in the Event Logs:
`Service cannot be started. System.Net.HttpListenerException (0x80004005): The process cannot access the file because it is being used by another process
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at Nancy.Hosting.Self.NancyHost.TryStartListener()
   at Nancy.Hosting.Self.NancyHost.StartListener()
   at Nancy.Hosting.Self.NancyHost.Start()
   at Seq.Server.ServiceProcess.ServerService.Start()
   at System.ServiceProcess.ServiceBase.ServiceQueuedMainCallback(Object state)`

And the Seq logs:
`{"@t":"2017-08-08T13:45:56.5164067Z","@mt":"Seq {SeqVersion} {ProcessWordSize}-bit running on .NET {DotNetVersion} and OS {OSCaption} ({OSVersion}) {OSWordSize}-bit","SeqVersion":"4.1.17","ProcessWordSize":64,"DotNetVersion":"4.0.30319.42000","OSCaption":"Microsoft Windows 8.1 Enterprise","OSVersion":"6.3.9600","OSWordSize":64,"SourceContext":"Seq.Server.Features.Diagnostics.EnvironmentInformationWriter"}
{"@t":"2017-08-08T13:45:57.3184459Z","@mt":"Error running the server application","@l":"Fatal","@x":"System.Net.HttpListenerException (0x80004005): The process cannot access the file because it is being used by another process\r\n   at System.Net.HttpListener.AddAllPrefixes()\r\n   at System.Net.HttpListener.Start()\r\n   at Nancy.Hosting.Self.NancyHost.TryStartListener()\r\n   at Nancy.Hosting.Self.NancyHost.StartListener()\r\n   at Nancy.Hosting.Self.NancyHost.Start()\r\n   at Seq.Server.ServiceProcess.ServerService.Start()"}
`
I was able to start the service manually.

I hope this helps identifying the issue.

**Comment by nblumhardt** [comment] 2017-08-08 21:01
Thanks for the follow-up, @ralsu091!

This error is sometimes raised when another service is listening on the same port, and sometimes when the account that the service is running under has inadequate permissions. Is it possible either case applies here?

To see what else might be listening, after a failure like this you could run:

```
netstat -o -n -a
```

as an admin user. I'd look out for apps like Skype that tend to make tricky use of various ports.

If the service is not running as "local system", then there could be a problem with the URL reservation in Windows - probably best to work through that via support email if it might be the case (we're support@getseq.net).

Thanks!

**Comment by nblumhardt** [comment] 2017-08-30 06:38
I'm able to consistently repro this on one machine now. Working to pinpoint the delay.

**Comment by nblumhardt** [comment] 2017-08-31 10:50
On my test machine, no amount of startup time optimisation would get rid of this, nor disabling CRL checking, etc.; I then realised the machine is still .NET 4.5.1 - upgraded it to 4.6.2, restarted Seq, and the problem was completely resolved. @laurencee is there a chance the .NET Framework on the machine in question is out of date?

The 4.2.14-pre build at https://getseq.net/Download includes the optimisations I was able to make, plus a couple of minor shut-down bug fixes I uncovered in the process. If anyone's seeing consistent timeouts on reboot, it'd be great to get your feedback on that build.

**Comment by laurencee** [comment] 2017-08-31 14:19
I'll check it out tomorrow. Due for a reboot anyway given a number of recent windows updates on that machine in particular.

**Comment by tsimbalar** [comment] 2017-09-01 11:21
> is there a chance the .NET Framework on the machine in question is out of date?

interesting ! We've had similar issues with the Seq service not starting automatically after a server restart during "patching parties"... I'll try to know which OS / .NET version is on that server, but I highly doubt it has been upgraded to .NET 4.6.2.

For what it's worth, we've also had similar issues with some of our in-house developed services that regularly fail to restart after the server reboots (even though they are configured as "automatic"). Those services where written in C#, using [TopShelf](is there a chance the .NET Framework on the machine in question is out of date?) , in case it's relevant.

**Comment by Suchiman** [comment] 2017-09-01 12:33
I have .NET Framework 4.7 installed on a Windows Server 2008 R2 and just yesterday i've observed Seq not starting. I've seen this a few times now and initially assumed, Seq crashed, but it was always after a restart and its not starting automatically despite being set to automatic startup and i cannot see any error.

**Comment by nblumhardt** [comment] 2017-09-01 21:50
@Suchiman @tsimbalar thanks for the additional info.

When I was able to reproduce it consistently, no Seq code would end up running in the process - no startup messages logged, and no error - this led me to investigate Authenticode CRL checking, which is known for causing issues for signed service binaries at start-up.

The 4.2.14-pre build includes a defensive flag intended to disable CRL checking for _seq.exe_, in case this is triggered on any of the target OS/framework combinations. If you have the opportunity to give that build at try, it would be interesting to hear whether there's any improvement.

(I should note, after the .NET Framework upgrade, the first service restart was slow - so may be worth watching out for in case it masks results.)

**Comment by laurencee** [comment] 2017-09-03 07:37
The service started fine on boot, forgot to check the .NET version. Will check tomorrow 👍

**Comment by tsimbalar** [comment] 2017-09-03 11:55
@nblumhardt out of curiosity, is it this flag ? 
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <runtime>
        <generatePublisherEvidence enabled="false"/>
    </runtime>
</configuration>
```

I'm a bit confused, as the [documentation](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/generatepublisherevidence-element) states : 
> In the .NET Framework 4 and later, this element has no effect on assembly load times. For more information, see the "Security Policy Simplification" section in Security Changes.

... but it also states : 

> We recommend that services use the `<generatePublisherEvidence>` element to improve startup performance. Using this element can also help avoid delays that can cause a time-out and the cancellation of the service startup.

What I understand is that it "used to slow stuff down stuff in .NET <4.0", but the doc may be wrong :)

**Comment by nblumhardt** [comment] 2017-09-03 21:30
@tsimbalar that's one of them :-) ... I found a few contradictory reports out there - it's possible the flag might actually have some effect on 4.5.1. 🤷‍♂️

**Comment by laurencee** [comment] 2017-09-04 23:05
The server Seq failed to start on boot on is running` .NET Framework 4.6.1`. Like I mentioned though, it didn't have any issues on the last reboot that happened.

The last reboot was applying a bunch of cumulative rollup patches for the past 2 months. (Server 2012 R2)

**Comment by nblumhardt** [comment] 2017-09-05 02:20
@laurencee thanks for the feedback; will be good to know how 4.2.14-pre (or the RTM equivalent) goes.

**Comment by tsimbalar** [comment] 2017-09-05 07:13
Turns out it also happens on my Dev machine, so it's way easier to get all the information I need :)

The service did not start after my PB rebooted (after an upgrade to VS 2017 Update3). I have restarted it several times and the Seq service still won't start automatically. I still get this in the Event Viewer : 


There is nothing in the log (there is actually not even a log file for today), which does seem to prove that the problem happens prior to the service starting.

**Seq** seems to be the only service that fails to start 

![image](https://user-images.githubusercontent.com/160544/30049300-5ecba194-921a-11e7-82c0-6e8309a424dd.png)


I am running : 
- Seq v4.1.17 (that's the version number or seq.exe)
- on Windows 8.1 Enterprise N
- with a multitude of .NET versions :p

[.NET Detector](https://www.raymond.cc/blog/how-to-check-what-version-of-microsoft-net-framework-is-installed-in-computer/) reports : 
```
Installed .NET Framework packages

.NET Framework 2.0 Service Pack 2   ver: 2.0.50727.4927
.NET Framework 3.0 Service Pack 2   ver: 3.0.30729.4926
.NET Framework 3.5 Service Pack 1   ver: 3.5.30729.4926
.NET Framework 4.6.1   ver: 4.6.01055

```

`clrver.exe` reports 
```
Microsoft (R) .NET CLR Version Tool  Version 4.6.1055.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Versions installed on the machine:
v2.0.50727
v4.0.30319
```
 
I'll try the latest (pre) version of Seq, see if it improves anything

**Comment by tsimbalar** [comment] 2017-09-05 07:27
with v4.2.14-pre .... still no luck 

![image](https://user-images.githubusercontent.com/160544/30049846-6ad74acc-921c-11e7-9ba2-11e4d5071ecc.png)

**Comment by tsimbalar** [comment] 2017-09-05 08:16
I've tried fiddling with `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control` `ServicesPipeTimeout` (setting it up to **120000 ms** for a service to start) based on this [Microsoft KB](https://support.microsoft.com/en-us/help/922918/a-service-does-not-start-and-events-7000-and-7011-are-logged-in-window) but appart from making my computer start up time way longer, that didn't solve the issue ...

![image](https://user-images.githubusercontent.com/160544/30051693-48f76d22-9223-11e7-9c58-0e611797d4c1.png)

**Comment by tsimbalar** [comment] 2017-09-05 08:30
FWIW fiddling with service dependencies in the registry (I know U_U ...) did not seem to help 

![image](https://user-images.githubusercontent.com/160544/30052267-3845f3f2-9225-11e7-934f-08a3e9d179c3.png)

**Comment by nblumhardt** [comment] 2017-09-06 07:40
Thanks for digging into it @tsimbalar - appreciate the help! Looks like you tried most things I did; it's a bit puzzling.

This one is getting close to the top of the list, I'll take another shot at it tomorrow and keep you posted.

**Comment by tsimbalar** [comment] 2017-09-11 05:44
This morning, after switching on my computer, it turns out Seq is running ... but if I restart my computer, the service won't ... 

I've tried a few times, and it looks like **the service starts properly when switching my PC offf and back on** , but **not in cases of a computer restart** ... this makes absolutely no sense !

**Comment by nblumhardt** [comment] 2017-09-11 21:53
That's an interesting additional data point!

The Windows services API notifies the service of various OS events like shut-down; I know we handle shutdown specifically, I wonder if the same notification or a different one is raised on restart? Going to investigate that angle today 👍

**Comment by nblumhardt** [comment] 2017-09-15 03:08
@tsimbalar one (possibly overly-optimistic) thought... If you extend the service pipe timeout, is there any way you can log in while the process is sitting there hung to collect a memory dump (e.g. via right-click in Task Manager processes list)? Thanks!

**Comment by tsimbalar** [comment] 2017-09-15 06:32
When I set `ServicesPipeTimeout` to a crazy value like `300000` (i.e. 5 minutes), the Seq service does eventually start on reboot ...


Here, you can see I restarted the computer (eventId 13 is the *shutdown*, eventId 20 is the *boot*)
![image](https://user-images.githubusercontent.com/160544/30468992-978e8e8e-99ee-11e7-9ae6-36e38b838eab.png)

... and Seq started about 2.5 minutes later, after a whole pile of junk has already started :). Here's the list of events in my *Application Event Viewer*
![image](https://user-images.githubusercontent.com/160544/30469044-d014ff36-99ee-11e7-88c1-398992a0b566.png)
![image](https://user-images.githubusercontent.com/160544/30469058-e421182a-99ee-11e7-88ee-b36f80547373.png)
![image](https://user-images.githubusercontent.com/160544/30469076-fc759568-99ee-11e7-9e5b-3e8482ddb355.png)
![image](https://user-images.githubusercontent.com/160544/30469099-1598dc08-99ef-11e7-9c42-d41c02b43665.png)


After *Seq* has started, I also see lots of events related to ESENT, but I guess that's normal :p

I'll send you:
- memory dump of Seq once it has started
- export of my Event Logs

**Comment by nblumhardt** [comment] 2017-09-18 03:14
Just adding the conclusions of my email discussion with @tsimbalar to the thread; Thibaud confirmed that the _Seq.exe_ executable hasn't been started by Windows yet while the delay occurs - there's no Seq process visible at all in Task Manager, until it finally starts successfully.

It'd be great to hear whether anyone's experience has been different.

I think this does suggest that the problem is to do with code signing or some other related aspect of the executable, rather than it being a hang (e.g. deadlock or timeout) in the Seq code itself.

Apart from CRL checking, which I think I ruled out on the machine that I could previously repro this on, I don't have any immediate ideas - I'll post here when I come up with another angle to attack this from, though.

**Comment by IanYates** [comment] 2017-09-18 23:48
I've got this happening on a few servers - increasingly frequently (as in, it very rarely happened anywhere, but not I'll see it a couple of times per day around the place).
I haven't had the luxury of digging in to see what's going on unfortunately.  Certainly starting the service manually gets it going, and it then stays going.  Reboots are not frequent so it's tricky to gather a data point.
I can see thought that all would be running at least .NET 4.6.1 or even 4.6.2.  A mix of Windows Server 2012, 2012 R2 and 2016 (and possibly a couple of 2008 R2 but I can't be 100% sure).

Another data point - the server I just noticed this on (and thus searched the issues repository here) is actually running Seq 4.0.60.

I'll try the pre-release but don't know when there will be another reboot to give more data unfortunately.

**Comment by nblumhardt** [comment] 2017-09-18 23:57
Thanks for the information, @IanYates 👍

**Comment by taspeotis** [comment] 2017-09-25 00:00
> Apart from CRL checking, which I think I ruled out on the machine that I could previously repro this on,

We are seeing this problem too and thought CRL checking might be the culprit, especially considering internet connectivity from our production servers is quite limited.

Two notes:

* Our networking gear seems to be configured to drop packets rather than reject them (even outbound packets...) so visiting http://crl.comodoca.com/COMODORSACodeSigningCA.crl results in failure after ~30 seconds rather than instantaneously.

* Permitting access to `crl.comodoca.com`, `crl.comodoca.com.cdn.cloudflare.net`, `ocsp.comodoca.com` and `ocsp.usertrust.com` did not fix the startup issue, despite being able to download the CRL in IE on the server.

**Comment by Suchiman** [comment] 2017-09-25 00:17
I have this occurring on a machine that has unrestricted fast outbound internet access, i don't think thats it.
I'm 95% positive that this is a regression in 4.x, haven't seen this happening in 3.x.

**Comment by nblumhardt** [comment] 2017-09-26 23:19
@Suchiman and @taspeotis, thanks for the analysis.

Robin, unfortunately I've got a one email support thread, as well as [this one](http://docs.getseq.net/discuss/5948f2d2290b95002464d234) on the discussion forum, that seem to suggest 3.4 also exhibits this behavior.

The machine I had that reliably reproduced this still hasn't had the issue again, following the .NET Framework upgrade. I wonder though, since it doesn't seem to be related to .NET version, whether the act of upgrading .NET was enough to flush out some kind of cache?

It's not much to go on, and clutching at straws, but would anyone with a readily-reproducible case of this be able to try ngening Seq.exe and see whether this might kick it over?

```
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\ngen.exe install Seq.exe
```

**Comment by taspeotis** [comment] 2017-09-27 00:34
Just tried ngen then reboot, the service did not start.

Also, with regards to *I then realised the machine is still .NET 4.5.1 - upgraded it to 4.6.2, restarted Seq, and the problem was completely resolved.* this server has the latest version of .NET 4.7. I would assume 4.7's bugfixes would supersede 4.6.2's.

**Comment by nblumhardt** [comment] 2017-09-27 21:18
Thanks for checking it out, @taspeotis 👍 Yes, I agree it's unlikely to be a .NET Framework version-specific issue.

**Comment by tsimbalar** [comment] 2017-09-29 05:37
> Just adding the conclusions of my email discussion with @tsimbalar to the thread; Thibaud confirmed that the Seq.exe executable hasn't been started by Windows yet while the delay occurs - there's no Seq process visible at all in Task Manager, until it finally starts successfully.

@nblumhardt my bad, I've tried something today, using [Process Monitor's boot logging](https://www.msigeek.com/6231/how-to-enable-system-boot-time-logging-using-process-monitor-tool) ... It turns out that the `Seq.exe` process is indeed invoked, and seems to be killed by Windows after about 30 seconds... 

- First occurrence of `Seq.exe`
![image](https://user-images.githubusercontent.com/160544/31002081-a9ceb6aa-a4e8-11e7-8f9b-8e1b20b7b964.png)

... about 3500 events i, between

- `Seq.exe` ending
![image](https://user-images.githubusercontent.com/160544/31002106-cc14bb56-a4e8-11e7-8ad1-190a319bcd1d.png)

The timestamps are consistent with the *you have 30 seconds to start a service* rule.

I'll send you the full ProcMon trace (that's biiiig)

**Comment by nblumhardt** [comment] 2017-09-30 03:42
Excellent! Great to have the data, I'll jump into it and let you know what I find, thanks @tsimbalar.

**Comment by taspeotis** [comment] 2017-10-02 11:26
If the process is actually starting and spending 30 seconds doing something (or nothing) it seems reasonable you could [procdump](https://docs.microsoft.com/en-us/sysinternals/downloads/procdump) the process before it terminates and then analyse it.

A bit low tech but just put a batch file to `procdump seq` on your desktop and log in just after the server boots up.

I assume @nblumhardt has the symbol files for Seq but if not dotPeek can reverse engineer .NET assemblies to PDB files.

**Comment by nblumhardt** [comment] 2017-10-02 23:03
Thanks for the suggestion @taspeotis - yes, we have the symbols stashed away 👍 

If the process is up, getting a dump _should_ be enough to solve this one. Would really love to get this one closed this week! :-)

**Comment by taspeotis** [comment] 2017-10-03 04:56
(Sorry if this covers the same territory as some of the service dependency comments above.)

I'm trying to get a process dump, just figuring out how to get procdump to run in between Seq failing to start and Remote Desktop Services starting. Without RDS running I can't RDP in to get the memory dump, but Seq timing out blocks RDS. I am going to wrangle with scheduling procdump at startup but some notes:

* Placing a dependency on `TermService` defers starting Seq until after Remote Desktop Services but ... then Seq starts and runs. (`sc config seq depend= TermService`)

* Placing a dependency on `RpcSs` (the only dependency of `TermService`) does not help. From investigating `RpcSs` is already running in advance of Seq without the dependency, anyway. (`sc config seq depend= RpcSs`)

Obviously Seq doesn't need Remote Desktop Services running, so a dependency might be missing from the following list (which are the services that run after Seq fails to start but before Remote Desktop Services starts).

```
"The Seq Log Server service ... did not respond ... in a timely fashion."

WinHTTP Web Proxy Auto-Discovery Service
Distributed Link Tracking Client
Windows Management Instrumentation
Windows Process Activation Service
World Wide Web Publishing Service
Windows Remote Management (WS-Management)
IP Helper
Server
Windows Update
Web Management Service
Portable Device Enumerator Service
Network List Service

Remote Desktop Services
```

**Comment by nblumhardt** [comment] 2017-10-03 05:05
Excellent, thanks for the update @taspeotis 👍 

We've tried a few service dependency "fixes" but haven't seen success thus far, it's interesting to know that `sc config seq depend= TermService` fixes the issue. Is this consistent for you across a few reboots?

Does the issue resolve if you use `sc config seq depend= iphlpsvc`? (My own Seq instance runs happily without `WinRM` running, so guess it is one of the dependencies of `WinRM` that you identified.

Thanks for sticking with this, really appreciate all the help!

**Comment by nblumhardt** [comment] 2017-10-03 05:08
Just adding one more possible thing to try, in case the dependency investigation turns out to be a dead end. Since the process seems to be loading, yet no events are ever written to Seq's internal log, it's a (remote) possibility that Seq could be hanging on opening its own log file.

To test this out, we could try:

```
seq config -k diagnostics.internalLoggingLevel -v Fatal
```

before restarting. I think this is a long shot, but if anyone with a reproducible case of the issue can try it, it'd be great to rule it out. Thanks :-)

**Comment by taspeotis** [comment] 2017-10-03 05:14
No problems re: investigation, just hoping to figure out what it is. I'll be digging into what's causing Seq to not start on boot later tonight or tomorrow though. If it *is* what I think it is, it looks like different systems will start different services in non-deterministic order so sometimes you'll get WMI started in advance of Seq by coincidence.

> My own Seq instance runs happily without WinRM

Windows Management Instrumentation is `Winmgmt`, not `WinRM`.

**Comment by tsimbalar** [comment] 2017-10-03 06:40
@taspeotis I think you're onto something with WMI in here :)

I've changed the "service timeout" on my machine to some crazy value like 5 minutes instead of 30 seconds ( https://serverfault.com/questions/622432/how-do-i-increase-windows-service-startup-timeout ) and enabled ProcMon boot log .... 

What I see there is that the `Seq.exe` process is up almost as soon as Windows boots (7:52:41 on the screenshots) 

![image](https://user-images.githubusercontent.com/160544/31111969-60f91304-a811-11e7-9975-1e14982048e6.png)

... and it's doing things (lots of things !) for a bit (I guess it's the whole .NET runtime dance, locating assemblies etc)


then nothing, then it's back for a bit after 1 min (at 7:53:41 precisely)
![image](https://user-images.githubusercontent.com/160544/31112498-5a149588-a814-11e7-9a3c-f3837a105dcc.png)

... and then nothing again for a while ...
... and then at 7:54:41it's back for good this time ...
![image](https://user-images.githubusercontent.com/160544/31112623-0adf3274-a815-11e7-8a20-bf8b99f6c223.png)

Somehow interestingly, references to WMI shortly before the process seems to "pause" : 
![image](https://user-images.githubusercontent.com/160544/31112813-256e1a64-a816-11e7-9295-5e1ba0193489.png)

and

![image](https://user-images.githubusercontent.com/160544/31112824-436cf2ce-a816-11e7-9f6b-e58a3d4397b8.png)


If I recall, some "diagnostics" were added as part of Seq v4.1 #594  ... Could it be that it adds a dependency on WMI somewhere ?

**Comment by taspeotis** [comment] 2017-10-03 06:44
I think the stack trace I put in https://github.com/datalust/seq-releases/issues/606#issuecomment-333738906 is pretty telling. It's calling into `System.Management` which [*provides access to a rich set of management information and management events about the system, devices, and applications instrumented to the Windows Management Instrumentation (WMI) infrastructure*](https://msdn.microsoft.com/en-us/library/mt481551(v=vs.110).aspx).

Also it might help to explain why the log isn't getting written. The Autofac container is building - so if the log is created by way of being a startable component, `Seq.Server.Features.Diagnostics.EnvironmentInformationWriter` is too and might beat it to starting. Although in this case `EnvironmentInformationWriter` isn't starting :)

**Comment by tsimbalar** [comment] 2017-10-03 07:40
For what it's worth : 
- `seq config -k diagnostics.internalLoggingLevel -v Fatal` doesn't seem to change anything  

... but once I have done 
```
sc.exe config seq depend= "Winmgmt"
```
![image](https://user-images.githubusercontent.com/160544/31114530-da3a7642-a81e-11e7-8c50-26eb667ac24b.png)

The Seq Service does start properly on reboot 🎉  (I tried a few times)

**Comment by nblumhardt** [comment] 2017-10-03 10:19
Awesome results! I'll create a new build that configures the `Winmgmt` dependency at install-time and post it so we can get some wider verification 👍

**Comment by nblumhardt** [comment] 2017-10-04 02:01
Hi all-

The installer at:

https://getseq.net/Download/Begin?version=4.2.17-pre

...has the dependency on Winmgmt specified. It would be great to hear whether this fixes the issue definitively.

Just a note: some changes in the MSI seem to cause an (unrelated) issue upgrading if the Seq service is running. If the installer hangs at "validating install", you need to stop the Seq service to proceed. Let me know if this happens, I'm investigating that one now :-)

Thanks!

**Comment by nblumhardt** [comment] 2017-10-05 02:24
Quick note, 4.1.18-pre, now on the downloads page, fixes the MSI issue :-)

**Comment by tsimbalar** [comment] 2017-10-05 06:46
Works fine for me (the 4.2.17-pre did too) 🎆

**Comment by nblumhardt** [comment] 2017-10-05 21:05
That could be the best news I've ever heard. Thanks for checking it out, and for all the help and investigation, @tsimbalar! It looks like you cracked it, @taspeotis 🥇 :-)

Thanks everyone on this thread for working through the issue, deeply appreciated.

**Closed by nblumhardt** 2017-10-05 21:05 UTC
Labels: bug

**Comment by taspeotis** [comment] 2017-10-05 23:51
All good, thanks for Seq. It's been a fantastic help to me.

**Comment by DylanTusler** [comment] 2018-02-13 01:29
Just reviewing this thread now, we've been having this problem with older versions of Seq. I love the interaction here. That's what community is all about. Well done on cracking this one.
