### ISSUE TITLE
Are server timestamps available?

### ISSUE THREAD

**Issue by javinovo** [datalust/seq-releases#474] opened 2016-08-25 14:06 UTC
We have a lot of issues with Windows 10 client machines having the wrong time set and we have noticed that the [Timestamp built-in property](http://docs.getseq.net/docs/built-in-properties-and-functions) contains the time from the Serilog client.

Is there any other property holding the time when the event was received in the server? 
If not, is there a way to attach a property through the API key?

**Comment by nblumhardt** [comment] 2016-08-26 00:04
Thanks for the note. This is a duplicate of #453 which is high on our list (I'll tag it with 3.4 as I think we should be able to address it there). Control will be via the API key :+1: 

Thanks again!

**Closed by nblumhardt** 2016-08-26 00:04 UTC
